### ISSUE TITLE
XLPFE running errors

### ISSUE THREAD

**Issue by mglgc** [LinaDongXMU/XLPFE#4]
Hi,
After a successful conda env XLPFE installation, the XLPFE.sh main script ends up with errors messages coming from the python scripts as I'm copying below. Please, could you give me some clues to fix it? Thank you very much in advance for your reply.

-------------------------
Traceback (most recent call last):
  File "/user/XLPFE-main/application/for_feature/pocket.py", line 17, in <module>
    if a[5].isalnum()==True:
IndexError: list index out of range
Traceback (most recent call last):
  File "/user/XLPFE-main/application/for_feature/fullprotein.py", line 17, in <module>
    if a[5].isalnum()==True:
IndexError: list index out of range
Traceback (most recent call last):
  File "/user/XLPFE-main/application/for_model/XLPFE.py", line 14, in <module>
    x_tests=transfer.fit_transform(x_test)
  File "/user/miniconda3/lib/python3.9/site-packages/sklearn/base.py", line 852, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/user/miniconda3/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 806, in fit
    return self.partial_fit(X, y, sample_weight)
  File "/user/miniconda3/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 841, in partial_fit
    X = self._validate_data(
  File "/user/miniconda3/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/user/miniconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 805, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 63)) while a minimum of 1 is required by StandardScaler.
cp: cannot stat 'results.csv': No such file or directory
---------------------------------

**Comment by mglgc** [comment]
Further clarifying, the issue comes from the pocket.py script:

Traceback (most recent call last):
  File "/user/XLPFE-main/application/for_feature/pocket.py", line 17, in <module>
    if a[5].isalnum()==True:
IndexError: list index out of range

**Comment by mglgc** [comment]
Digging into the code I realized if the pocket pdb files contain chain identifiers (PDB column #22) the pocket.py script will reproduce such issue. Fixed by leaving blank that PDB column.


> Further clarifying, the issue comes from the pocket.py script:
> 
> Traceback (most recent call last): File "/user/XLPFE-main/application/for_feature/pocket.py", line 17, in if a[5].isalnum()==True: IndexError: list index out of range

**Comment by LinaDongXMU** [comment]
[examples](https://github.com/LinaDongXMU/XLPFE/tree/main/examples) have pocket.pdb and protein.pdb to be referred. Congratulations on being able to debug on yourself.

**Comment by mglgc** [comment]
Anyway, thanks for your reply.

> [examples](https://github.com/LinaDongXMU/XLPFE/tree/main/examples) have pocket.pdb and protein.pdb to be referred. Congratulations on being able to debug on yourself.
